version: '3'
services:
  jekyll:
    build: 
      context: ./
      dockerfile: jekyll.dockerfile
    ports:
      - "4000:4000"

  grunt:
    build: 
      context: ./
      dockerfile: grunt.dockerfile
    ports:
      - "35729:35729"

